sudo: required
services: 
    - docker

before_install:
    - docker build -t jalarcon/docker-tut-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jalarcon/docker-tut-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-tut-react"
    env: "DockerTutReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-157356677452"
    bucket_path: "docker-tut-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
