sudo: required
services: 
    - docker

before_install:
    - docker build -t jalarcon/docker-tut-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jalarcon/docker-tut-react npm run test
